version: "3.7"
networks:
  overlay:
volumes:
  ghost-data:
secrets:
  jmoyers.org-certchain.crt:
    file: ./.ssl/jmoyers.org-certchain.crt
  jmoyers.org.key:
    file: ./.ssl/jmoyers.org.key
configs:
  nginx_conf:
    file: https/nginx.conf
    name: nginx${stack_configs_nginx_conf_file}
services:
  static:
    image: static
    ports:
      - 8000:8000
    networks:
      - overlay
    environment:
      - STATIC_PORT=8000
  hugo:
    image: hugo_jmoyers_org
    ports:
      - 1313:1313
  https:
    image: nginx:1.16.0-alpine
    secrets:
      - jmoyers.org-certchain.crt
      - jmoyers.org.key
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 80:80
    networks:
      - overlay
    command: ["nginx", "-g", "daemon off;"]
