version: "3.7"
networks:
  overlay:
volumes:
  docker-registry-data:
  ghost-data:
secrets:
  jmoyers.org-certchain.crt:
    file: ./.ssl/jmoyers.org-certchain.crt
  jmoyers.org.key:
    file: ./.ssl/jmoyers.org.key
configs:
  nginx_conf:
    file: https/nginx.conf
    name: nginx${stack_configs_nginx_conf_file}
services:
  docker-registry:
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - docker-registry-data:/var/lib/registry
    networks:
      - overlay
  static:
    image: static
    ports:
      - 8000:8000
    networks:
      - overlay
    environment:
      - STATIC_PORT=8000
  ghost:
    image: ghost:2.25.1-alpine
    volumes:
      - ghost-data:/var/lib/ghost/content
    ports:
      - 2368:2368
    environment:
      - url=https://192.241.232.130/blog/
    networks:
      - overlay
  https:
    image: nginx:1.16.0-alpine
    secrets:
      - jmoyers.org-certchain.crt
      - jmoyers.org.key
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 80:80
    networks:
      - overlay
    command: ["nginx", "-g", "daemon off;"]
