version: "3.5"
networks:
  overlay:
secrets:
  jmoyers.org-certchain.crt:
    file: ./.ssl/jmoyers.org-certchain.crt
  bundle.crt:
    file: ./.ssl/sectigo/jmoyers_org.ca-bundle
  jmoyers.org.key:
    file: ./.ssl/jmoyers.org.key
  dhparams.pem:
    file: ./.ssl/dh/dhparams.pem
services:
  https:
    image: jmoyers_org_static
    ports:
      - 80:80
      - 443:443
    secrets:
      - dhparams.pem
      - bundle.crt
      - jmoyers.org-certchain.crt
      - jmoyers.org.key
    networks:
      - overlay
    command: ["nginx", "-g", "daemon off;"]
