name = "jmoyers.org"
license = "MIT"

description = "The theme for jmoyers.org"
homepage = "https://github.com/jmoyers/jmoyers.org"
min_version = "0.25.1"

[author]
	name = "jmoyers"
	homepage = "https://jmoyers.org"
