#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

NODE01=${1:-$(terraform output -state=$DIR/../terraform.tfstate public_ip)}

cat << ENDFILE > $DIR/../../ansible/hosts
[nodes]
$NODE01 ansible_ssh_user=root ansible_private_key_file=~/.ssh/id_rsa
ENDFILE
