- hosts: localhost
  connection: local
  tasks:
  - name: Build static docker image, send build context to node01
    shell: |
      docker -H ssh://node01 build ../ -t jmoyers_org_static
  - name: Update https service to latest image
    shell: |
      docker -H ssh://node01 service update jmoyers_org_https --force

