- hosts: nodes
  gather_facts: False
  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt -y upgrade && apt install -y python-minimal)

- hosts: nodes
  tasks:
  - name: Install and start docker
    shell: |
      apt -y update
      apt -y upgrade
      apt install -y docker.io
      systemctl start docker
      systemctl enable docker

  # Single node swarm, firewall is blocking port, don't think we can not
  # advertise, doesn't really matter
  - name: Start docker swarm
    shell: |
      docker swarm leave --force
      docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
    ignore_errors: yes

- hosts: localhost
  connection: local
  tasks:
  - name: Deploy stack to docker swarm
    shell: |
      docker -H ssh://node01 stack deploy -c ../docker-compose.yml jmoyers_org
  - name: Build static docker image, send build context to node01
    shell: |
      docker -H ssh://node01 build ../ -t jmoyers_org_static

